title: INF-2200 Computer architecture and organization - Fall 2022

description: > # this means to ignore newlines until "contact:"
  INF-2200 Computer architecture and organization, fall 2022, UiT The Arctic University of Norway

contact:
  email: lars.ailo.bongo@uit.no
  name: Lars Ailo Bongo

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
