title: Course name (edit _config.yml)

description: > # this means to ignore newlines until "contact:"
  Course description.

contact:
  email: firstname.lastname@uit.no
  name: Firstname Lastname (edit _config.yml)

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
